server:
  port: 8081

---
spring:
  application:
    name: api-dev
  config:
    import: "optional:configserver:http://localhost:8888"

---
management:
  endpoints:
    web:
      exposure:
        include: refresh
